[profiles]
personal = "https://github.com/user/chezuser"
work = "https://github.com/org/dotfiles-work"

[templates]
self-python-template = { source = "https://github.com/user/python-template", manager = "copier" }
self-zola-template = "https://github.com/user/zola-template"  # Default: `copier`
work-cookiecutter-template = { source = "https://github.com/org/uv-template", manager = "cruft" }

[workspace]
destination = "~/workspace"   # default clone destination

[workspace.owners]
user = { source = "https://github.com/user" }

[workspace.repos]  # extra repos not fully covered by an owner group
open-source = "https://github.com/open/source"

[brew]
perso-packages = { manifest = "~/.config/athome/Brewfile" }
